default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: adminate-server_development

test:
  <<: *default
  database: adminate-server_test

staging:
  <<: *default
  database: adminate-server_staging
  username: adminate-server
  password: <%= ENV['ADMINATE-SERVER_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: adminate-server_production
  username: adminate-server
  password: <%= ENV['ADMINATE-SERVER_DATABASE_PASSWORD'] %>